baseURL = "https://no5gforhumanity.com/"
languageCode = "en-us"
title = "No 5G for Humanity"
mainSections = ["research-studies", "events"]
paginate = 6
summarylength = 66


[params]
  author = "Richard"
  authorbio = "Advicate against 5G."

[build.environment]
  TZ = "America/Toronto"

