baseURL = "https://no5gforhumanity.com/"
languageCode = "en-us"
title = "No 5G for Humanity"
mainSections = ["Research Studies", "Events"]
paginate = 6
summarylength = 66


[params]
  author = "Richard"
  authorbio = "Advicate against 5G."

