baseURL = "https://no-5g-for-humanity.netlify.app/"
languageCode = "en-us"
title = "5G Website"
mainSections = ["Research Studies"]
paginate = 6
summarylength = 66


[params]
  author = "Richard"
  authorbio = "Advicate against 5G."

