[[redirects]]
  from = "https://no5gforhumanity.ca/"
  to = "https://no5gforhumanity.com/"
  status = 301
  force = false
  query = {path = ":path"}
  conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}

  [build.environment]
  TZ = "America/New_York"